In [1]:
import pandas as pd

vendas = pd.read_csv('01.amazon_sales_dataset (1).csv')
vendas.info()
vendas.columns
vendas

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        10000 non-null  str
 1   order_date      10000 non-null  str
 2   ship_date       10000 non-null  str
 3   delivery_date   10000 non-null  str
 4   order_status    10000 non-null  str
 5   customer_id     10000 non-null  str
 6   customer_name   10000 non-null  str
 7   country         10000 non-null  str
 8   state           10000 non-null  str
 9   city            10000 non-null  str
 10  product_id      10000 non-null  str
 11  product_name    10000 non-null  str
 12  category        10000 non-null  str
 13  sub_category    10000 non-null  str
 14  brand           10000 non-null  str
 15  quantity        10000 non-null  int64
 16  unit_price      10000 non-null  float64
 17  discount        10000 non-null  float64
 18  shipping_cost   10000 non-null  float64
 19  total_sales     10000 non-null  float64
 20  payment_method  10000 non-null  str
dtypes: float64(4), int64(1), str(16)
memory usage: 1.6 MB

,order_id,order_date,ship_date,delivery_date,order_status,customer_id,customer_name,country,state,city,...,product_name,category,sub_category,brand,quantity,unit_price,discount,shipping_cost,total_sales,payment_method
0,A10000,2026-01-31,2026-01-31,2026-01-08,Delivered,C5691,Ricky Potter,India,South Carolina,New Joe,...,without,Home,Furniture,Doyle-Jordan,3,42467.79,0.26,60.85,94339.3438,Card
1,A10001,2026-01-20,2026-02-03,2026-02-03,Delivered,C9811,Chris Davenport,India,Tennessee,Madisonmouth,...,school,Home,Furniture,Davis LLC,2,36138.76,0.24,112.96,55043.8752,COD
2,A10002,2026-01-15,2026-02-07,2026-01-03,Delivered,C7341,Timothy Gallagher,India,Iowa,East Larryberg,...,I,Electronics,Laptop,Watson and Sons,4,47148.93,0.14,64.11,162256.4292,UPI
3,A10003,2026-01-18,2026-01-15,2026-01-20,Delivered,C4012,Angela Collins,India,Kentucky,South Margaretshire,...,step,Electronics,Laptop,"Sandoval, Buckley and Solis",1,18487.99,0.06,114.15,17492.8606,Card
4,A10004,2026-01-27,2026-01-04,2026-01-23,Delivered,C1328,David Davidson DDS,India,North Dakota,Velasquezview,...,bit,Home,Kitchen,"Key, Bautista and Bowen",1,1742.25,0.10,40.47,1608.4950,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,A19995,2026-02-08,2026-01-07,2026-01-10,Delivered,C3522,Kelly Bryant,India,Alabama,West Kimberlyview,...,question,Electronics,Laptop,Leach Inc,3,20844.54,0.01,101.13,62009.4138,UPI
9996,A19996,2026-01-17,2026-01-23,2026-02-03,Delivered,C9510,Kristina Barnes,India,Colorado,Jamesborough,...,item,Fashion,Footwear,Wells-Taylor,4,25467.29,0.15,93.64,86682.4260,COD
9997,A19997,2026-01-17,2026-01-11,2026-01-15,Delivered,C3630,Samuel Anderson,India,Montana,Lake Richard,...,leave,Fashion,Footwear,"Stuart, Johnson and Peterson",3,27680.47,0.29,39.30,58998.7011,COD
9998,A19998,2026-01-08,2026-01-18,2026-02-07,Delivered,C8299,April King,India,Georgia,Millerview,...,too,Fashion,Clothing,"Perry, Vargas and Mason",2,13572.25,0.13,62.82,23678.5350,COD
9999,A19999,2026-01-31,2026-01-30,2026-02-08,Delivered,C7848,Jennifer Rogers,India,Alabama,Taylorstad,...,total,Home,Kitchen,"Sawyer, Copeland and Allison",2,9009.02,0.23,94.25,13968.1408,UPI

In [2]:
analise_vendas = vendas.drop(columns=["order_id", "customer_id", "product_id"])
analise_vendas = analise_vendas.rename(columns={
    "order_date": "Data",
    "ship_date": "Data_Envio",
    "delivery_date": "Data_Entrega",
    "order_status": "Status_Entrega",
    "customer_name": "Nome_Cliente",
    "country": "País",
    "state": "Estado",
    "city": "Cidade",
    "product_name": "Produto",
    "category": "Categoria",
    "sub_category": "Sub_categoria",
    "brand": "Marca_Produto",
    "quantity": "Quantidade",
    "unit_price": "Preço",
    "discount": "Desconto_sobre_Receita",
    "shipping_cost": "Frete",
    "total_sales": "Receita_Menos_Desconto_Mais_Frete",
    "payment_method": "Método_Pagamento"
})
analise_vendas.head()

,Data,Data_Envio,Data_Entrega,Status_Entrega,Nome_Cliente,País,Estado,Cidade,Produto,Categoria,Sub_categoria,Marca_Produto,Quantidade,Preço,Desconto_sobre_Receita,Frete,Receita_Menos_Desconto_Mais_Frete,Método_Pagamento
0,2026-01-31,2026-01-31,2026-01-08,Delivered,Ricky Potter,India,South Carolina,New Joe,without,Home,Furniture,Doyle-Jordan,3,42467.79,0.26,60.85,94339.3438,Card
1,2026-01-20,2026-02-03,2026-02-03,Delivered,Chris Davenport,India,Tennessee,Madisonmouth,school,Home,Furniture,Davis LLC,2,36138.76,0.24,112.96,55043.8752,COD
2,2026-01-15,2026-02-07,2026-01-03,Delivered,Timothy Gallagher,India,Iowa,East Larryberg,I,Electronics,Laptop,Watson and Sons,4,47148.93,0.14,64.11,162256.4292,UPI
3,2026-01-18,2026-01-15,2026-01-20,Delivered,Angela Collins,India,Kentucky,South Margaretshire,step,Electronics,Laptop,"Sandoval, Buckley and Solis",1,18487.99,0.06,114.15,17492.8606,Card
4,2026-01-27,2026-01-04,2026-01-23,Delivered,David Davidson DDS,India,North Dakota,Velasquezview,bit,Home,Kitchen,"Key, Bautista and Bowen",1,1742.25,0.10,40.47,1608.4950,UPI

In [3]:
analise_vendas["Data"] = pd.to_datetime(analise_vendas["Data"], format="%Y-%m-%d")

analise_vendas["Data_Envio"] = pd.to_datetime(analise_vendas["Data_Envio"], format="%Y-%m-%d")

analise_vendas["Data_Entrega"] = pd.to_datetime(analise_vendas["Data_Entrega"], format="%Y-%m-%d")
                                                
analise_vendas.sample(20)


analise_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Data                               10000 non-null  datetime64[us]
 1   Data_Envio                         10000 non-null  datetime64[us]
 2   Data_Entrega                       10000 non-null  datetime64[us]
 3   Status_Entrega                     10000 non-null  str
 4   Nome_Cliente                       10000 non-null  str
 5   País                               10000 non-null  str
 6   Estado                             10000 non-null  str
 7   Cidade                             10000 non-null  str
 8   Produto                            10000 non-null  str
 9   Categoria                          10000 non-null  str
 10  Sub_categoria                      10000 non-null  str
 11  Marca_Produto                      10000 non-null  str
 12  Quantidade                         10000 non-null  int64
 13  Preço                              10000 non-null  float64
 14  Desconto_sobre_Receita             10000 non-null  float64
 15  Frete                              10000 non-null  float64
 16  Receita_Menos_Desconto_Mais_Frete  10000 non-null  float64
 17  Método_Pagamento                   10000 non-null  str
dtypes: datetime64[us](3), float64(4), int64(1), str(10)
memory usage: 1.4 MB

In [4]:
coluna_alvo = "Desconto_sobre_Receita"

total_desconto = analise_vendas[coluna_alvo].sum()
desconto_mediano = analise_vendas[coluna_alvo].median()
desconto_medio = analise_vendas[coluna_alvo].mean()
menor_desconto = analise_vendas[coluna_alvo].min()
maior_desconto = analise_vendas[coluna_alvo].max()

print(f'1.Desconto Total de Receitas foi de: {total_desconto:,.2f}')
print(f'2.Desconto Mediano sobre as Receitas foi de: {desconto_mediano:,.2f}')
print(f'3.Desconto Média sobre as Receitas foi de: {desconto_medio:,.2f}')
print(f'4.Menor Desconto Individual sobre as Receitas foi de: {menor_desconto:,.2f}')
print(f'5.Maior Desconto Individual sobre as Receitas foi de: {maior_desconto:,.2f}')

1.Desconto Total de Receitas foi de: 1,499.68
2.Desconto Mediano sobre as Receitas foi de: 0.15
3.Desconto Média sobre as Receitas foi de: 0.15
4.Menor Desconto Individual sobre as Receitas foi de: 0.00
5.Maior Desconto Individual sobre as Receitas foi de: 0.30

O total de descontos concedidos foi de 1.499,68. O desconto médio foi de 0,15 (15%) (o mesmo valor, também, foi encontrado para o desconto mediano). O menor desconto concedido foi de 0,00 e o maior desconto concedido foi de 0,30 (30%).

In [5]:
import numpy as np

coluna_usada = "Desconto_sobre_Receita"

q1 = np.percentile(analise_vendas[coluna_usada], 25)
q2 = np.percentile(analise_vendas[coluna_usada], 50)
q3 = np.percentile(analise_vendas[coluna_usada], 75)

print(f'Primeiro Quartil (Q1 - Menores Descontos): {q1:,.2f}')
print(f'Segundo Quartil (Q2 - Mediana dos Descontos): {q2:,.2f}')
print(f'Terceiro Quartil (Q3 - Maiores Descontos): {q3:,.2f}')

Primeiro Quartil (Q1 - Menores Descontos): 0.07
Segundo Quartil (Q2 - Mediana dos Descontos): 0.15
Terceiro Quartil (Q3 - Maiores Descontos): 0.22

Ao ordenar os dados dos Descontos_sobre_Receita vemos que os 25% primeiros descontos montam a $0,07. A mediana desses descontos foi de $0,15 e os 75% mais elevados descontos foi de $0,22.

In [6]:
delta_media_mediana = desconto_medio - q2
distancia_Percentual = desconto_medio/q2

assimetria = analise_vendas[coluna_alvo].skew()

print('--- Relatório Estatístico de Negócio ---')
print(f'A média dos descontos de vendas é {desconto_medio:,.2f}')
print(f'A mediana (valor central) dos descontos é  {q2:,.2f}')
print(f'O Delta (a diferença Financeira) entre elas é {delta_media_mediana:,.2f}')
print('\n--- Análise Comportamental ---\n')
print(f'Distância Relativa entre elas {distancia_Percentual:,.2f}')

if abs (distancia_Percentual -1) < 0.10:
    print(f'INFERÊNCIA: Baixa Dispersão. A média é confiável para representar a coluna.')
elif abs(distancia_Percentual -1) < 0.25:
    print(f'INFERÊNCIA: Dispersão Moderada. Fique atento a extremos, a média começa a mentir.')
else:
    print(f'INFERÊNCIA: Alta Dispersão. A média NÃO é confiável, foque na mediana.')

print(f'Grau de Assimetria (Skewness): {assimetria:,.4f}')
if assimetria > 0.5:
    print(f'INFERÊNCIA (Assimetria Positiva): Nossas vendas têm uma cauda loga para a direita. Os grandes clientes são minoria, todavia eles faturam valores expressivos puxando a venda média para cima.')
elif assimetria < -0.5:
    print(f'INFERÊNCIA (Assimetria Negativa): Nossas vendas têm uma cauda longa para esquerda. O valor médio está sendo puxado para baixo por um grande volume de vendas baratas, talvez pela liquidação.')
else:
    print(f'INFERÊNCIA (Simétrica): Distribuição Equilibrada. Média e mediana estão bem próximas.')

--- Relatório Estatístico de Negócio ---
A média dos descontos de vendas é 0.15
A mediana (valor central) dos descontos é  0.15
O Delta (a diferença Financeira) entre elas é -0.00

--- Análise Comportamental ---

Distância Relativa entre elas 1.00
INFERÊNCIA: Baixa Dispersão. A média é confiável para representar a coluna.
Grau de Assimetria (Skewness): -0.0042
INFERÊNCIA (Simétrica): Distribuição Equilibrada. Média e mediana estão bem próximas.

Temos uma distribuição dos dados do Desconto_sobre_receita simétrica. Desse modo, a média é bem representativa da distribuição e, por consequência, podemos usá-la, sem problema algum.